name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo
        ports:
        - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
      
      # TODO: configure it
      neo4j:
        image: neo4j:latest
        env:
          NEO4J_AUTH: neo4j/your_password
          NEO4J_USERNAME: neo4j
          NEO4J_PASSWORD: your_password
        ports:
        - 7474:7474
        - 7687:7687

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose